### ISSUE TITLE
NTAG215 cards not working

### ISSUE THREAD

**Issue by Fyb3roptik** [marcoalbarelli/nfctools-aer#2]
Getting this error:

```
10-16 23:18:52.001 2159-2187/eu.marcoalbarelli.android.usbtest E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: eu.marcoalbarelli.android.usbtest, PID: 2159
    org.nfctools.NfcException: org.nfctools.NfcException: Unknown memory size 62
        at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:96)
        at org.nfctools.mf.ul.Type2NfcTagListener.handleTag(Type2NfcTagListener.java:52)
        at eu.marcoalbarelli.android.usbtest.ReaderStateChangeListener.onStateChange(ReaderStateChangeListener.java:45)
        at com.acs.smartcard.Reader$a.run(SourceFile:846)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.nfctools.NfcException: Unknown memory size 62
        at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:87)
        at org.nfctools.mf.ul.Type2NfcTagListener.handleTag(Type2NfcTagListener.java:52) 
        at eu.marcoalbarelli.android.usbtest.ReaderStateChangeListener.onStateChange(ReaderStateChangeListener.java:45) 
        at com.acs.smartcard.Reader$a.run(SourceFile:846) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by marcoalbarelli** [comment]
This project is very old. Most likely you should provide a PR for updating the nfctools library.
Feel free to do so.

**Comment by Fyb3roptik** [comment]
I ended up using NTAG213 cards instead

**Comment by marcoalbarelli** [comment]
Glad you found a solution :)
